services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - path: ./local.env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["sh", "entrypoint.sh"]


  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metrominute
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 10s
      retries: 20