metro_minute:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: metrominute
      schema: core

    container:
      type: postgres
      host: db
      user: postgres
      password: postgres
      port: 5432
      dbname: metrominute
      schema: core

    gcp:
      type: postgres
      host: "{{ env_var('DATABASE_HOST') }}"
      user: "{{ env_var('DATABASE_USER') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      port: "{{ env_var('DATABASE_PORT') | int }}"
      dbname: metrominute
      schema: core
      connect_timeout: 30
